cask_args appdir: '/Applications'

tap 'caskroom/cask'
tap 'homebrew/bundle'
tap 'caskroom/versions'

brew 'coreutils'
brew 'dnsmasq'
brew 'thefuck'
brew 'wget'
brew 'zsh'
brew 'zsh-completions'
brew 'libtiff' 
brew 'libtool'
brew 'youtube-dl'
brew 'ssh-audit'

cask 'calibre'
cask 'firefox'
cask 'hipchat'
cask 'iterm2'
cask 'postman'
cask 'skype'
cask 'sourcetree'
cask 'sublime-text'
cask 'transmission'
cask 'virtualbox'
cask 'virtualbox-extension-pack'
cask 'vlc'
cask 'keepingyouawake'
cask 'spotify-notifications'
