cask_args appdir: '/Applications'

tap 'caskroom/cask'
tap 'homebrew/bundle'
tap 'caskroom/versions'

brew 'coreutils'
brew 'dnsmasq'
brew 'thefuck'
brew 'wget'
brew 'zsh'
brew 'zsh-completions'

cask 'calibre'
cask 'firefox'
cask 'hipchat'
cask 'iterm2'
cask 'postman'
cask 'skype'
cask 'sourcetree'
cask 'sublime-text3'
cask 'transmission'
cask 'virtualbox'
cask 'virtualbox-extension-pack'
cask 'vlc'
