#Product aliases
alias update_product_openapi_config="docker run --rm -it --net=host -v ~/Documents/projects/applications/proxy/src/config/autoload:/templates registry.rd.alphanetworks.tv/tucano/v1/consul-template-php7/consul-template-php7:0.1 -consul-addr \"127.0.0.1:8500\" -template \"/templates/dump.tpl:/consul-template/data/dump.yml:php  /consul-template/data/template-renderer.php -c /templates/config.yml -d /consul-template/data/dump.yml\" -once"
alias update_product_wecare_config="docker run --rm -it --net=host -v ~/Documents/projects/applications/wecare/application/configs:/configs -v ~/Documents/projects/applications/wecare/src/config/autoload:/templates registry.rd.alphanetworks.tv/tucano/v1/consul-template-php7/consul-template-php7:0.1 -consul-addr \"127.0.0.1:8500\" -template \"/configs/templates/dump.tpl:/consul-template/data/dump.yml:php  /consul-template/data/template-renderer.php -c /configs/templates/config.yml -d /consul-template/data/dump.yml\" -template \"/templates/dump.tpl:/consul-template/data/dump_zf2.yml:php  /consul-template/data/template-renderer.php -c /templates/config.yml -d /consul-template/data/dump_zf2.yml\" -once"

alias update_product_toolbox_config="docker run --rm -it --net=host -v ~/Documents/projects/applications/TlcToolbox/src/config/autoload:/templates registry.rd.alphanetworks.tv/tucano/v1/consul-template-php7/consul-template-php7:0.1 -consul-addr \"127.0.0.1:8500\" -template \"/templates/dump.tpl:/consul-template/data/dump.yml:php  /consul-template/data/template-renderer.php -c /templates/config.yml -d /consul-template/data/dump.yml\" -once"

alias update_product_soa_transactions_config="docker run --rm -it --net=host -v ~/Documents/projects/soa/transactions/src/config/autoload:/templates registry.rd.alphanetworks.tv/tucano/v1/consul-template-php7/consul-template-php7:0.1 -consul-addr \"127.0.0.1:8500\" -template \"/templates/dump.tpl:/consul-template/data/dump.yml:php  /consul-template/data/template-renderer.php -c /templates/config.yml -d /consul-template/data/dump.yml\" -once"
alias update_product_soa_workflow_config="docker run --rm -it --net=host -v ~/Documents/projects/soa/workflow/src/config/autoload:/templates registry.rd.alphanetworks.tv/tucano/v1/consul-template-php7/consul-template-php7:0.1 -consul-addr \"127.0.0.1:8500\" -template \"/templates/dump.tpl:/consul-template/data/dump.yml:php  /consul-template/data/template-renderer.php -c /templates/config.yml -d /consul-template/data/dump.yml\" -once"

alias update_product_driver_paypal_config="docker run --rm -it --net=host -v ~/Documents/projects/drivers/PayPal/src/config/autoload:/templates registry.rd.alphanetworks.tv/tucano/v1/consul-template-php7/consul-template-php7:0.1 -consul-addr \"127.0.0.1:8500\" -template \"/templates/dump.tpl:/consul-template/data/dump.yml:php  /consul-template/data/template-renderer.php -c /templates/config.yml -d /consul-template/data/dump.yml\" -once"
alias update_product_driver_answecare_config="docker run --rm -it --net=host -v ~/Documents/projects/drivers/AnsWecare/src/config/autoload:/templates registry.rd.alphanetworks.tv/tucano/v1/consul-template-php7/consul-template-php7:0.1 -consul-addr \"127.0.0.1:8500\" -template \"/templates/dump.tpl:/consul-template/data/dump.yml:php  /consul-template/data/template-renderer.php -c /templates/config.yml -d /consul-template/data/dump.yml\" -once"
alias update_product_driver_verimatrix_config="docker run --rm -it --net=host -v ~/Documents/projects/drivers/VerimatrixOmi/src/config/autoload:/templates registry.rd.alphanetworks.tv/tucano/v1/consul-template-php7/consul-template-php7:0.1 -consul-addr \"127.0.0.1:8500\" -template \"/templates/dump.tpl:/consul-template/data/dump.yml:php  /consul-template/data/template-renderer.php -c /templates/config.yml -d /consul-template/data/dump.yml\" -once"
alias update_product_driver_tlccrm_config="docker run --rm -it --net=host -v ~/Documents/projects/drivers/TelecentroCrm/src/config/autoload:/templates registry.rd.alphanetworks.tv/tucano/v1/consul-template-php7/consul-template-php7:0.1 -consul-addr \"127.0.0.1:8500\" -template \"/templates/dump.tpl:/consul-template/data/dump.yml:php  /consul-template/data/template-renderer.php -c /templates/config.yml -d /consul-template/data/dump.yml\" -once"

#OBE aliases
alias update_obe_cpeproxy_voo_config="docker run --rm -it --net=host -v ~/Documents/projects/applications/CpeProxy_orange/config/autoload:/templates -v ~/Documents/projects/applications/CpeProxy_orange/config/autoload/consul-voo.tpl:/templates/consul.tpl registry.rd.alphanetworks.tv/tucano/v1/consul-template-php7/consul-template-php7:0.1 -consul-addr \"127.0.0.1:8500\" -template \"/templates/dump.tpl:/consul-template/data/dump.yml:php  /consul-template/data/template-renderer.php -c /templates/config-voo.yml -d /consul-template/data/dump.yml\" -once"
alias update_obe_cpeproxy_telenet_config="docker run --rm -it --net=host -v ~/Documents/projects/applications/CpeProxy_orange/config/autoload:/templates -v ~/Documents/projects/applications/CpeProxy_orange/config/autoload/consul-telenet.tpl:/templates/consul.tpl registry.rd.alphanetworks.tv/tucano/v1/consul-template-php7/consul-template-php7:0.1 -consul-addr \"127.0.0.1:8500\" -template \"/templates/dump.tpl:/consul-template/data/dump.yml:php  /consul-template/data/template-renderer.php -c /templates/config-telenet.yml -d /consul-template/data/dump.yml\" -once"
alias update_obe_mocktool_config="docker run --rm -it --net=host -v ~/Documents/projects/applications/mocktool_orange/application/configs:/configs registry.rd.alphanetworks.tv/tucano/v1/consul-template-php7/consul-template-php7:0.1 -consul-addr \"127.0.0.1:8500\" -template \"/configs/templates/dump.tpl:/consul-template/data/dump.yml:php  /consul-template/data/template-renderer.php -c /configs/templates/config.yml -d /consul-template/data/dump.yml\" -once"
alias update_obe_openapi_config="docker run --rm -it --net=host -v ~/Documents/projects/applications/proxy_orange/src/config/autoload:/templates registry.rd.alphanetworks.tv/tucano/v1/consul-template-php7/consul-template-php7:0.1 -consul-addr \"127.0.0.1:8500\" -template \"/templates/dump.tpl:/consul-template/data/dump.yml:php  /consul-template/data/template-renderer.php -c /templates/config.yml -d /consul-template/data/dump.yml\" -once"
alias update_obe_webform_proxy_config="docker run --rm -it --net=host -v ~/Documents/projects/applications/webform_proxy_orange/src/config/autoload:/templates -v ~/Documents/projects/applications/webform_proxy_orange/src/config/autoload/consul.tpl:/templates/consul.tpl registry.rd.alphanetworks.tv/tucano/v1/consul-template-php7/consul-template-php7:0.1 -consul-addr \"127.0.0.1:8500\" -template \"/templates/dump.tpl:/consul-template/data/dump.yml:php  /consul-template/data/template-renderer.php -c /templates/config.yml -d /consul-template/data/dump.yml\" -once"
alias update_obe_wecare_config="docker run --rm -it --net=host -v ~/Documents/projects/applications/wecare_orange/application/configs:/configs -v ~/Documents/projects/applications/wecare_orange/src/config/autoload:/templates registry.rd.alphanetworks.tv/tucano/v1/consul-template-php7/consul-template-php7:0.1 -consul-addr \"127.0.0.1:8500\" -template \"/configs/templates/dump.tpl:/consul-template/data/dump.yml:php  /consul-template/data/template-renderer.php -c /configs/templates/config.yml -d /consul-template/data/dump.yml\" -template \"/templates/dump.tpl:/consul-template/data/dump_zf2.yml:php  /consul-template/data/template-renderer.php -c /templates/config.yml -d /consul-template/data/dump_zf2.yml\" -once"
alias update_obe_wemanage_config="docker run --rm -it --net=host -v ~/Documents/projects/applications/wemanage_orange/application/configs:/configs -v ~/Documents/projects/applications/wemanage_orange/src/config/autoload:/templates registry.rd.alphanetworks.tv/tucano/v1/consul-template-php7/consul-template-php7:0.1 -consul-addr \"127.0.0.1:8500\" -template \"/configs/templates/dump.tpl:/consul-template/data/dump.yml:php  /consul-template/data/template-renderer.php -c /configs/templates/config.yml -d /consul-template/data/dump.yml\" -template \"/templates/dump.tpl:/consul-template/data/dump_zf2.yml:php  /consul-template/data/template-renderer.php -c /templates/config.yml -d /consul-template/data/dump_zf2.yml\" -once"

alias update_obe_driver_celltracker_config="docker run --rm -it --net=host -v ~/Documents/projects/drivers/CellTracker/src/config/autoload:/templates registry.rd.alphanetworks.tv/tucano/v1/consul-template-php7/consul-template-php7:0.1 -consul-addr \"127.0.0.1:8500\" -template \"/templates/dump.tpl:/consul-template/data/dump.yml:php  /consul-template/data/template-renderer.php -c /templates/config.yml -d /consul-template/data/dump.yml\" -once"
alias update_obe_driver_cordb_config="docker run --rm -it --net=host -v ~/Documents/projects/drivers/CorDB/src/config/autoload:/templates registry.rd.alphanetworks.tv/tucano/v1/consul-template-php7/consul-template-php7:0.1 -consul-addr \"127.0.0.1:8500\" -template \"/templates/dump.tpl:/consul-template/data/dump.yml:php  /consul-template/data/template-renderer.php -c /templates/config.yml -d /consul-template/data/dump.yml\" -once"
alias update_obe_driver_cgn_config="docker run --rm -it --net=host -v ~/Documents/projects/drivers/CGN/src/config/autoload:/templates registry.rd.alphanetworks.tv/tucano/v1/consul-template-php7/consul-template-php7:0.1 -consul-addr \"127.0.0.1:8500\" -template \"/templates/dump.tpl:/consul-template/data/dump.yml:php  /consul-template/data/template-renderer.php -c /templates/config.yml -d /consul-template/data/dump.yml\" -once"
alias update_obe_driver_feasibility_config="docker run --rm -it --net=host -v ~/Documents/projects/drivers/Feasibility/src/config/autoload:/templates registry.rd.alphanetworks.tv/tucano/v1/consul-template-php7/consul-template-php7:0.1 -consul-addr \"127.0.0.1:8500\" -template \"/templates/dump.tpl:/consul-template/data/dump.yml:php  /consul-template/data/template-renderer.php -c /templates/config.yml -d /consul-template/data/dump.yml\" -once"
alias update_obe_driver_fluviusfiber_config="docker run --rm -it --net=host -v ~/Documents/projects/drivers/FluviusFiber/src/config/autoload:/templates registry.rd.alphanetworks.tv/tucano/v1/consul-template-php7/consul-template-php7:0.1 -consul-addr \"127.0.0.1:8500\" -template \"/templates/dump.tpl:/consul-template/data/dump.yml:php  /consul-template/data/template-renderer.php -c /templates/config.yml -d /consul-template/data/dump.yml\" -once"
alias update_obe_driver_kairos_config="docker run --rm -it --net=host -v ~/Documents/projects/drivers/Kairos/src/config/autoload:/templates registry.rd.alphanetworks.tv/tucano/v1/consul-template-php7/consul-template-php7:0.1 -consul-addr \"127.0.0.1:8500\" -template \"/templates/dump.tpl:/consul-template/data/dump.yml:php  /consul-template/data/template-renderer.php -c /templates/config.yml -d /consul-template/data/dump.yml\" -once"
alias update_obe_driver_mediationzone_config="docker run --rm -it --net=host -v ~/Documents/projects/drivers/MediationZone/src/config/autoload:/templates registry.rd.alphanetworks.tv/tucano/v1/consul-template-php7/consul-template-php7:0.1 -consul-addr \"127.0.0.1:8500\" -template \"/templates/dump.tpl:/consul-template/data/dump.yml:php  /consul-template/data/template-renderer.php -c /templates/config.yml -d /consul-template/data/dump.yml\" -once"
alias update_obe_driver_ngw_config="docker run --rm -it --net=host -v ~/Documents/projects/drivers/NGW/src/config/autoload:/templates registry.rd.alphanetworks.tv/tucano/v1/consul-template-php7/consul-template-php7:0.1 -consul-addr \"127.0.0.1:8500\" -template \"/templates/dump.tpl:/consul-template/data/dump.yml:php  /consul-template/data/template-renderer.php -c /templates/config.yml -d /consul-template/data/dump.yml\" -once"
alias update_obe_driver_ovh_config="docker run --rm -it --net=host -v ~/Documents/projects/drivers/OVH/src/config/autoload:/templates registry.rd.alphanetworks.tv/tucano/v1/consul-template-php7/consul-template-php7:0.1 -consul-addr \"127.0.0.1:8500\" -template \"/templates/dump.tpl:/consul-template/data/dump.yml:php  /consul-template/data/template-renderer.php -c /templates/config.yml -d /consul-template/data/dump.yml\" -once"
alias update_obe_driver_serviceorder_config="docker run --rm -it --net=host -v ~/Documents/projects/drivers/ServiceOrder/src/config/autoload:/templates registry.rd.alphanetworks.tv/tucano/v1/consul-template-php7/consul-template-php7:0.1 -consul-addr \"127.0.0.1:8500\" -template \"/templates/dump.tpl:/consul-template/data/dump.yml:php  /consul-template/data/template-renderer.php -c /templates/config.yml -d /consul-template/data/dump.yml\" -once"
alias update_obe_driver_telenet_config="docker run --rm -it --net=host -v ~/Documents/projects/drivers/Telenet/src/config/autoload:/templates registry.rd.alphanetworks.tv/tucano/v1/consul-template-php7/consul-template-php7:0.1 -consul-addr \"127.0.0.1:8500\" -template \"/templates/dump.tpl:/consul-template/data/dump.yml:php  /consul-template/data/template-renderer.php -c /templates/config.yml -d /consul-template/data/dump.yml\" -once"
alias update_obe_driver_tmmmlo_config="docker run --rm -it --net=host -v ~/Documents/projects/drivers/Tmmmlo/src/config/autoload:/templates registry.rd.alphanetworks.tv/tucano/v1/consul-template-php7/consul-template-php7:0.1 -consul-addr \"127.0.0.1:8500\" -template \"/templates/dump.tpl:/consul-template/data/dump.yml:php  /consul-template/data/template-renderer.php -c /templates/config.yml -d /consul-template/data/dump.yml\" -once"
alias update_obe_driver_voo_config="docker run --rm -it --net=host -v ~/Documents/projects/drivers/Voo/src/config/autoload:/templates registry.rd.alphanetworks.tv/tucano/v1/consul-template-php7/consul-template-php7:0.1 -consul-addr \"127.0.0.1:8500\" -template \"/templates/dump.tpl:/consul-template/data/dump.yml:php  /consul-template/data/template-renderer.php -c /templates/config.yml -d /consul-template/data/dump.yml\" -once"
alias update_obe_driver_zappware_config="docker run --rm -it --net=host -v ~/Documents/projects/drivers/Zappware/src/config/autoload:/templates registry.rd.alphanetworks.tv/tucano/v1/consul-template-php7/consul-template-php7:0.1 -consul-addr \"127.0.0.1:8500\" -template \"/templates/dump.tpl:/consul-template/data/dump.yml:php  /consul-template/data/template-renderer.php -c /templates/config.yml -d /consul-template/data/dump.yml\" -once"
alias update_obe_driver_zappwarecloud_config="docker run --rm -it --net=host -v ~/Documents/projects/drivers/ZappwareCloud/src/config/autoload:/templates registry.rd.alphanetworks.tv/tucano/v1/consul-template-php7/consul-template-php7:0.1 -consul-addr \"127.0.0.1:8500\" -template \"/templates/dump.tpl:/consul-template/data/dump.yml:php  /consul-template/data/template-renderer.php -c /templates/config.yml -d /consul-template/data/dump.yml\" -once"
alias update_obe_driver_road65_config="docker run --rm -it --net=host -v ~/Documents/projects/drivers/Road65/config/consul:/templates registry.rd.alphanetworks.tv/tucano/v1/consul-template-php7/consul-template-php7:0.1 -consul-addr \"127.0.0.1:8500\" -template \"/templates/dump.tpl:/consul-template/data/dump.yml:php  /consul-template/data/template-renderer.php -c /templates/config.yml -d /consul-template/data/dump.yml\" -once"

alias update_obe_soa_transactions_config="docker run --rm -it --net=host -v ~/Documents/projects/soa/transactions_orange/src/config/autoload:/templates registry.rd.alphanetworks.tv/tucano/v1/consul-template-php7/consul-template-php7:0.1 -consul-addr \"127.0.0.1:8500\" -template \"/templates/dump.tpl:/consul-template/data/dump.yml:php  /consul-template/data/template-renderer.php -c /templates/config.yml -d /consul-template/data/dump.yml\" -once"
alias update_obe_soa_workflow_config="docker run --rm -it --net=host -v ~/Documents/projects/soa/workflow_orange/src/config/autoload:/templates registry.rd.alphanetworks.tv/tucano/v1/consul-template-php7/consul-template-php7:0.1 -consul-addr \"127.0.0.1:8500\" -template \"/templates/dump.tpl:/consul-template/data/dump.yml:php  /consul-template/data/template-renderer.php -c /templates/config.yml -d /consul-template/data/dump.yml\" -once"
alias update_obe_driver_nttdata_config="docker run --rm -it --net=host -v ~/Documents/projects/drivers/nttdata/config/consul:/templates registry.rd.alphanetworks.tv/tucano/v1/consul-template-php7/consul-template-php7:0.1 -consul-addr \"127.0.0.1:8500\" -template \"/templates/dump.tpl:/consul-template/data/dump.yml:php  /consul-template/data/template-renderer.php -c /templates/config.yml -d /consul-template/data/dump.yml\" -once"
